name: 'Get Next Nuget Package Version from GitHub'
description: 'Action for getting Next Nuget Package Version from GitHub'
author: 'rexebin'

# Define your inputs here.
inputs:
  org:
    description: 'Organization name'
    required: true
  packageName:
    description: 'Package name'
    required: true
  token:
    description: 'GitHub token'
    required: true

# Define your outputs here.
outputs:
  version:
    description: 'The version of the package'

runs:
  using: node20
  main: dist/index.js
